/**
 * Stable application environment contract.
 *
 * The deployer's `worker-configuration.d.ts` is generated by Wrangler and
 * ignored because it depends on a private wrangler.jsonc. These application
 * fields stay here so a clean checkout has the same type contract. Email is
 * optional — self-hosted instances run without it.
 */

declare global {
  interface Env {
    DB: D1Database;
    MEDIA: R2Bucket;
    ASSETS: Fetcher;
    DEPLOYMENT_MODE: "self_hosted" | "hosted";
    ADMIN_KEY: string;

    /**
     * Cloudflare Email Service `send_email` binding. Present only when
     * the deployment declares one; `emailProvider()` checks for it.
     */
    EMAIL?: { send(message: unknown): Promise<{ messageId?: string }> };

    /** Resend API key, used when no EMAIL binding is bound. Secret. */
    RESEND_API_KEY?: string;

    /** Sender address for transactional email. */
    EMAIL_FROM?: string;

    /**
     * Canonical origin for links in emails. Never derived from the Host
     * header, which would let an attacker redirect reset links.
     */
    PUBLIC_BASE_URL?: string;

    /** "true" | "false". Defaults by deployment mode when unset. */
    EMAIL_VERIFICATION_REQUIRED?: string;
  }
}

export {};
